### PR TITLE
Add codecov upload to dotnet and python

### PR DESCRIPTION
**Pull request by djorgensendk**

### CODE REVIEW

**Comment by djorgensendk** [comment]
@LayZeeDK use of CodeCov is a decision made by the architect @Sondergaard during PI planning. SonarCloud also was mentioned as a possibility.

**Comment by LayZeeDK** [comment]
I see, @djorgensendk. Thank you for enlightening me.

@Sondergaard do we have an Architecture Decision Record (ADR)? It would be helpful to track requirements, options considered, pros and cons as well as background for decisions.

**Review by CodeReaper — APPROVED** [review]

**Comment by Sondergaard** [comment]
@LayZeeDK - we do not have any ADR for the decision to use CodeCov. 

We startede implementing CodeCov before SonarCloud. I am not sure that the two products are feature equivalent.

**Comment by LayZeeDK** [comment]
Thank you for your reply, @Sondergaard. Do we have ADRs for DataHub at all? 👀

**Pull request merged**
